server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: springBoardProjectAshurin

  config:
    import:
      - properties/datasource.yml

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_SOURCE_URL}
    username: ${DATABASE_SOURCE_USERNAME}
    password: ${DATABASE_SOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.web.servlet: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdb.extract: trace
